services:
  web:
    image: aps_web:latest
    volumes:
      - ./web:/app
    tty: true
    ports:
      - "${PORT:-3000}:3000"
    env_file:                   
      - ./.env
    restart: unless-stopped # 除非手動停止，否則異常停止會自動重啟 適合 server 類型的服務

  rtsp:
    image: bluenviron/mediamtx:latest
    container_name: synlab-rtsp
    ports:
      - "1935:1935"
      - "8554:8554"
    # volumes:
      # - ./rtsp/mediamtx.yml:/mediamtx.yml:ro

  yolocam1:
    build: { context: ./yolo/src, dockerfile: Dockerfile }
    depends_on:
      - rtsp
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    # 把 CLI 參數放在 command（對應到 ENTRYPOINT 後面的參數）
    command: ["--stream","rtsp://ip:port/stream-name","--yolo","person,dog,cat"]

# volumes:
#    synclab_ws: {}

