services:
  web:
    image: aps_web:latest
    volumes:
      - ./web:/app
    tty: true
    ports:
      - "${PORT:-3000}:3000"
    env_file:                   
      - ./.env
    restart: unless-stopped # 除非手動停止，否則異常停止會自動重啟 適合 server 類型的服務

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554" # RTSP
      - "8080:8080" # HTTP

  # cam1:
  #   image: rtsp:v_3
  #   ports:
  #     - "5000:5000" # Flask Web Server Port
  #   # depends_on:
  #   #   - mediamtx
  #   volumes:
  #     - ./rtsp/src/:/app/
  #   env_file:
  #     - ./.env
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
  #     - OPENCV_FFMPEG_CAPTURE_OPTIONS=rtsp_transport;tcp
  #   working_dir: /app
  #   # 執行 python3 程式並傳遞 CLI 參數
  #   command: 
  #     - python3
  #     - simple_web_stream.py
  #     - --stream
  #     - "rtsp://admin:cctv-8888@220.130.204.161:504/unicast/c3/s1/live"

  rtsptoweb:
    image: ghcr.io/deepch/rtsptoweb:latest
    ports:
      - "8083:8083" # Web Server Port
    volumes:
      - ./rtsptoweb/config.json:/config/config.json 
    networks: [ live_net ]

    caddy:
      image: caddy:alpine
      container_name: live-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
        - caddy_data:/data
        - caddy_config:/config
      depends_on: [ rtsptoweb ]
      networks: [ live_net ]

  networks:
    live_net:

  volumes:
    caddy_data:
    caddy_config:
# volumes
#    synclab_ws: {}

